version: '3.8'
networks:
  default:
    external: true
    name: ${NETWORK_NAME}
services:
  optinetflow:
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=${PORT}